import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ExtraProviders } from "./providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Astradur Stefansson",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ExtraProviders>
          <main className="bg-background text-foreground">{children}</main>
        </ExtraProviders>
      </body>
    </html>
  )
}
