import { Layout } from "@/components/layout/Layout"
import { Theme } from "@radix-ui/themes"
import "@radix-ui/themes/styles.css"
import { Analytics } from "@vercel/analytics/react"
import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { getAuthorizationUrl, getUser } from "./auth"
import "./globals.css"
import { ExtraProviders } from "./providers"

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Astradur Stefansson",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getUser()

  if (user === undefined) {
    return <div>...Loading</div>
  }

  const userAuthenticated = user.isAuthenticated
  const authKitUrl = getAuthorizationUrl("projects/gdc")

  return (
    <html lang="en">
      <body>
        <ExtraProviders>
          <Theme>
            <main>
              <Layout
                userAuthenticated={userAuthenticated}
                authKitUrl={authKitUrl}
              >
                {children}
              </Layout>
            </main>
            <Analytics />
          </Theme>
        </ExtraProviders>
      </body>
    </html>
  )
}
