import "./globals.css"
import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { ExtraProviders } from "./providers"
import { Analytics } from "@vercel/analytics/react"
import { Layout } from "@/components/layout/Layout"

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Astradur Stefansson",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen font-sans antialiased ${fontSans.variable}`}
      >
        <ExtraProviders>
          <main>
            <Layout>{children}</Layout>
          </main>
          <Analytics />
        </ExtraProviders>
      </body>
    </html>
  )
}
